[FIX] no notion profile photo error (#91)
morethanmin/morethan-log pull request #97
Opened 2023-01-30 12:42 UTC by itjustbong

## Description

Corrected the error that may occur if there is no picture in the notion profile.

If user don't have a profile picture, the avatar.svg to be showed.

## Related tickets

https://github.com/morethanmin/morethan-log/issues/91

## PR Checklist

- [x] I have read the [Contributing Guide](./docs/CONTRIBUTING.md)
- [x] I have written documents and tests, if needed.

2023-01-30 23:31 UTC, morethanmin requested changes
제가 이슈처리하려 했었는데... 감사합니다 👍  코멘트 남겨드린 부분만 한번 확인 부탁드리겠습니다 ㅎㅎ

2023-01-30 23:31 UTC, morethanmin commented on src/containers/Detail/components/PostDetail/PostHeader.tsx
> +                    src={data.author[0].profile_photo || "/avatar.svg"}
이부분 `site.comfig.js` 에 상수로 정의되어있어서 해당 값을 사용해주실 수 있으실까요?
`"/avatar.svg"` -> `CONFIG.profile.image` 이렇게 바꿔주시면 될 것 같아요!

2023-01-31 03:43 UTC, itjustbong commented on src/containers/Detail/components/PostDetail/PostHeader.tsx
> +                    src={data.author[0].profile_photo || "/avatar.svg"}
앗, 넵 상수로 있는 부분은 미쳐 확인하지 못했네요..ㅜㅜ
수정해보겠습니다!!!
확인 감사합니다 🥳

2023-01-31 05:04 UTC, morethanmin approved these changes

2023-01-31 05:09 UTC, merged

2023-01-31 05:09 UTC, morethanmin commented
merged!